baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed




## Default html head settings
description: "Ndizera Eddy: Freelance Senior Software Developer specializing in Python, Django, and building business software from scratch. Let's work together!"
title: "Ndizera Eddy | Freelance Senior Software Developer | Python & Django Expert"
lang: en

## Contacts
github: https://github.com/edd19
linkedin: https://www.linkedin.com/in/eddy-ndizera-277181105/
email: eddyndizera@ndizera.com

cv: "/assets/pdf/cv_ndizera_eddy_english.pdf"
cv_french: "/assets/pdf/cv_ndizera_eddy_francais.pdf"

