baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed




## Default html head settings
description: "Ndizera Eddy: Freelance Senior Software Developer specializing in Python, Django, and building business software from scratch. Let's work together!"
title: "Ndizera Eddy | Freelance Senior Software Developer | Python & Django Expert"
lang: en

## Contacts
github: https://github.com/edd19
linkedin: https://www.linkedin.com/in/eddy-ndizera-277181105/
email: eddyndizera@ndizera.com

cv: "/assets/pdf/cv_ndizera_eddy_english.pdf"
cv_french: "/assets/pdf/cv_ndizera_eddy_francais.pdf"

schema_markup: '{
        "@context": "https://schema.org",
        "@type": "Person",
        "name": "Ndizera Eddy",
        "image": "https://www.ndizera.com/assets/img/profile.jpg",
        "description": "Senior Freelance Software Developer",
        "address": {
          "@type": "PostalAddress",
          "addressLocality": "Brussels",
          "addressCountry": "Belgium"
        },
        "email": "{{ site.email }}",
        "jobTitle": "Freelance Senior Software Developer",
        "skills": "Python, Django, Full-Stack Development",
        "url": "https://www.ndizera.com"
      }'

